const LOAD_COMPANIES = 'LOAD_COMPANIES';
const LOAD_COMPANY = 'LOAD_COMPANY';
const EDIT_COMPANY = 'EDIT_COMPANY';
const DELETE_COMPANY = 'DELETE_COMPANY';
const CREATE_COMPANY = 'CREATE_COMPANY';

export {LOAD_COMPANY, LOAD_COMPANIES, DELETE_COMPANY, EDIT_COMPANY, CREATE_COMPANY}