const LOAD_PRODUCTS = 'LOAD_PRODUCTS';
const LOAD_PRODUCT = 'LOAD_PRODUCT';
const EDIT_PRODUCT = 'EDIT_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';
const CREATE_PRODUCT = 'CREATE_PRODUCT';

export {LOAD_PRODUCT, LOAD_PRODUCTS, DELETE_PRODUCT, EDIT_PRODUCT, CREATE_PRODUCT}