const LOAD_TICKETS = 'LOAD_TICKETS';
const LOAD_TICKET = 'LOAD_TICKET';
const CREATE_TICKET = 'CREATE_TICKET';
const EDIT_TICKET = 'EDIT_TICKET';
const DELETE_TICKET = 'DELETE_TICKET';

export {
    LOAD_TICKET, LOAD_TICKETS, CREATE_TICKET, DELETE_TICKET, EDIT_TICKET
}